apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: chatbot-1731319648220-gitops
  description: This is GitOps manifest for chatbot-1731319648220   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: chatbot-1731319648220
    janus-idp.io/tekton: chatbot-1731319648220 
    backstage.io/kubernetes-id: chatbot-1731319648220 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:chatbot-1731319648220
